# Generated by Django 5.2.14 on 2026-05-20 06:58

import employee.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[employee.validators.validate_employee_id_field]),
        ),
    ]
