# Generated by Django 5.1.15 on 2026-05-20 04:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyVehicleMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('licence_number', models.CharField(max_length=50, unique=True)),
                ('licence_photo', models.ImageField(blank=True, null=True, upload_to='driver_licences/')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NonReturnableGatePass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonReturnableGatePassItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutwardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnableGatePass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnableGatePassItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('truck_photo', models.ImageField(blank=True, null=True, upload_to='trucks/')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('tempo', 'Tempo'), ('pickup', 'Pickup'), ('van', 'Van'), ('two_wheeler', 'Two Wheeler'), ('other', 'Other')], default='truck', max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='VisitorBaggage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitorEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GateTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('truck_photo_at_entry', models.ImageField(blank=True, null=True, upload_to='gate_photos/%Y/%m/%d/')),
                ('number_of_passengers', models.PositiveSmallIntegerField(default=0)),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('inward', 'Inward'), ('outward', 'Outward'), ('returnable', 'Returnable'), ('non_returnable', 'Non Returnable'), ('visitor', 'Visitor'), ('company_vehicle', 'Company Vehicle')], default='inward', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='gate.driver')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_transactions', to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='gate.truck')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InwardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor_name_raw', models.CharField(blank=True, max_length=255)),
                ('challan_number', models.CharField(blank=True, max_length=100)),
                ('invoice_image', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/%d/')),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invoice_received', models.BooleanField(default=False)),
                ('ocr_raw_response', models.JSONField(blank=True, null=True)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('invoice_uploaded', 'Invoice Uploaded'), ('pending_verification', 'Pending Verification'), ('grn_generated', 'GRN Generated'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=30)),
                ('grn_number', models.CharField(blank=True, max_length=100)),
                ('grn_date', models.DateTimeField(blank=True, null=True)),
                ('stores_remarks', models.TextField(blank=True)),
                ('rejection_category', models.CharField(blank=True, choices=[('damaged', 'Damaged'), ('wrong_material', 'Wrong Material'), ('qty_mismatch', 'Quantity Mismatch'), ('quality_failure', 'Quality Failure'), ('wrong_po', 'Wrong PO'), ('other', 'Other')], max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('guard_remarks', models.TextField(blank=True)),
                ('gate_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inward_entry', to='gate.gatetransaction')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inward_entries', to='orders.purchaseorder')),
                ('stores_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_inward_entries', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inward_entries', to='orders.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InwardEntryStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inward_status_changes', to=settings.AUTH_USER_MODEL)),
                ('inward_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='gate.inwardentry')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='InwardItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('quantity_invoiced', models.CharField(max_length=50)),
                ('quantity_received', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('inward_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gate.inwardentry')),
                ('po_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_items', to='orders.purchaseorderitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
