# Generated by Django 5.2.14 on 2026-05-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0003_inward_flow_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardentry',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('acknowledged', 'Acknowledged'), ('completed', 'Completed')], default='pending_verification', max_length=30),
        ),
    ]
