# Generated by Django 5.2.14 on 2026-05-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0005_gate_management_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesacknowledgment',
            name='rejection_category',
            field=models.CharField(blank=True, choices=[('damaged', 'Damaged'), ('wrong_material', 'Wrong Material'), ('qty_mismatch', 'Quantity Mismatch'), ('quality_failure', 'Quality Failure'), ('wrong_po', 'Wrong PO'), ('other', 'Other')], max_length=30),
        ),
    ]
